# fly.toml app configuration file generated for misty-feather-7515 on 2023-09-14T18:40:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-feather-7515"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
