# fly.toml app configuration file generated for hidden-leaf-8317 on 2023-09-10T17:06:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "https://hidden-leaf-8317.fly.dev/"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
