# fly.toml app configuration file generated for blue-star-6947 on 2023-09-11T08:20:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-star-6947"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
